### ISSUE TITLE
Javascript combatibility problem

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#390]
IE 10 and 11 do not support backtick.

**Comment by fnielsen** [comment]
Also default parameters in functions is a problem with Microsoft Internet Exploere (IE) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

Solutions: 
- Avoid supporting IE (September 2017 browser share is ~8% https://en.wikipedia.org/wiki/Microsoft_Edge or 12% according to others). Microsoft Edge supports Javascript better and I suppose the rate of market share for IE will continuously drop.
- Use Babel.js which "might be considered overkill" https://twitter.com/larswillighagen/status/999215173394227200
- Use the usually way of making combatility multiline. This means that the SPARQL will be infested by JavaScript, which is not a pretty solution.
- Put SPARQL in separate files which are then fetched with ajax. Could be an intereting solution. Would support styling and checking better.

**Comment by fnielsen** [comment]
To my surprise Konqueror works in version 5.0.97.

**Comment by rasmuserik** [comment]
I think we should either decide on whether we want to use resources to support IE at the this time. And also document which browsers we want to test/support. (I'll also run into this with the code I am writing).

My suggestion is at least to test in Safari, Firefox and a Chromium-based browser. And to test on tablet and mobile as well as on desktop. As a part of #785, I'll document which browsers we target/support.

@fnielsen what do you think?

(Google Chrome, Microsoft Edge, Samsung Internet, Opera, Brave, etc. are all using the Chromium rendering engine. I do not know if we need to support IE – it has gone below 1% browser market share worldwide and requires much more work than the others, – as it does not implement recent standards).
